### ISSUE TITLE
Replace the HUD code for Side Objectives with ZScript.

### ISSUE THREAD

**Issue by catoidi** [catoidi/box-party-demo#3]
So, I want there to be a hotkey you can press at anytime that you can use to check which side objectives you've done and what you need to do. I've already coded this in ACS, but it's got some glaring issues and I want to rewrite it in ZScript to allow for more flexibility.

**Comment by idiotbitz** [comment]
Maybe I could use the already existing ACS to send data over to the zscript HUD? I'll look into this at some point.

**Comment by catoidi** [comment]
Done :)

The side quest UI has been streamlined a bit as well. you now view your quests by opening the automap, instead of having a dedicated keybind.
