### ISSUE TITLE
Finish drawing the rest of the pixel SmallFont.

### ISSUE THREAD

**Issue by catoidi** [catoidi/box-party-demo#5]
The font I drew for Box Party is ~25% done. For any english dialogue, this is a non-issue. But the issue becomes immediately noticeable if you change the interface's language to something not english.

To be clear, the characters will still appear just fine. But they currently do not match the art style of Box Party. I should fix this soon.

**Comment by idiotbitz** [comment]
Removing high priority tag for now.

**Comment by catoidi** [comment]
both fonts in the game have been replaced with a new HD font.

as far as im aware, it does come with non-english characters.
